name: Deploy CrunchApp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, churchapp]

    steps:
      - name: Atualizar servidor
        run: |
          set -e
          cd /root/CrunchApp
          git pull origin main
          docker compose up -d --build web api
