name: Deploy CrunchApp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Atualizar servidor
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/CrunchApp
            git pull origin main
            npm install
            npm --prefix api install
            npm --prefix web install
            npm --prefix api run prisma:deploy
            npm --prefix api run prisma:generate
            npm run web:build
            pm2 restart all
